#!/bin/bash
set -e

DB_FILE="/opt/laudio/laudio.db"
CONF_FILE="/etc/apache2/conf.d/laudio_apache.conf"
AUDIO_SYMLINK="/opt/laudio/media/audio"

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then

    # Source debconf library.
    . /usr/share/debconf/confmodule

    # Remove my changes to the db.
    if [ -e $DB_FILE ]; then
        rm $DB_FILE
    fi

    if [ -e $CONF_FILE ]; then
        rm $CONF_FILE
    fi

    if [ -e $AUDIO_SYMLINK ]; then
        rm $AUDIO_SYMLINK
    fi
    
    db_purge
    update-rc.d apache2 restart
fi

if [ "$1" = "remove" ]; then

    # Source debconf library.
    . /usr/share/debconf/confmodule

    if [ -e $DB_FILE ]; then
        rm $DB_FILE
    fi

    if [ -e $CONF_FILE ]; then
        rm $CONF_FILE
    fi

    if [ -e $AUDIO_SYMLINK ]; then
        rm $AUDIO_SYMLINK
    fi

    # Remove my changes to the db.
    db_purge
    update-rc.d apache2 restart
fi

