#!/bin/bash
set -e

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    rm /etc/apache2/conf.d/laudio_apache.conf
    db_purge
fi

if [ "$1" = "remove" ]; then

    # Source debconf library.
    . /usr/share/debconf/confmodule

    update-rc.d apache2 restart

    # Remove my changes to the db.
    db_purge
fi

